name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # checkout 代码库
      - uses: actions/checkout@v2

      # 安装和使用 Node.js 版本管理器 nvm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # 构建项目
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # 自动升级版本号
      - name: Auto-increment package version
        uses: bahmutov/npm-auto-versions@v2.6.0
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # 发布到 GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # 创建新的 release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.npm_package_version }}
          release_name: Release v${{ env.npm_package_version }}
          body: Release v${{ env.npm_package_version }}
